name: seqtk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - libgcc=14.2.0=h767d61c_2
  - libgomp=14.2.0=h767d61c_2
  - libzlib=1.3.1=hb9d3cd8_2
  - seqtk=1.4=h577a1d6_3
  - zlib=1.3.1=hb9d3cd8_2
prefix: /home/kristina/miniconda3/envs/seqtk
